name: Build sqldef

on:
  push:
    branches:
      - "main"
  schedule:
    - cron: "26 * * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-mysqldef:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build
        with:
          repository: https://github.com/k0kubun/sqldef.git
          imageName: mysqldef
          context: sqldef
          dockerfile: sqldef/mysqldef.Dockerfile
          platforms: |
            linux/amd64
            linux/arm64
            linux/i386

  build-psqldef:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build
        with:
          repository: https://github.com/k0kubun/sqldef.git
          imageName: psqldef
          context: sqldef
          dockerfile: sqldef/psqldef.Dockerfile
          platforms: |
            linux/amd64
            linux/arm64
            linux/i386

  build-mssqldef:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build
        with:
          repository: https://github.com/k0kubun/sqldef.git
          imageName: mssqldef
          context: sqldef
          dockerfile: sqldef/mssqldef.Dockerfile
          platforms: |
            linux/amd64
            linux/arm64
            linux/i386
