name: Build sqldef

on:
  push:
    branches:
      - "main"
  schedule:
    - cron: "26 * * * *"

jobs:
  build-mysqldef:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build
        with:
          repository: https://github.com/k0kubun/sqldef.git
          imageName: mysqldef
          context: sqldef
          dockerfile: sqldef/mysqldef.Dockerfile
          platforms: |
            linux/amd64
            linux/arm64
            linux/i386
